orbs:
  aws-eks: circleci/aws-eks@1.1.0
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-cli: circleci/aws-cli@3.1.0
  node: circleci/node@2.0.2

jobs:
  deploy-dev:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - run:
          name: Deploy-Dev.
          command: ssh ec2-user@13.234.33.67 './test-docker.sh';
version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          ###context myContext
          #create-repo: true
          dockerfile: test8/Dockerfile
          no-output-timeout: 20m
          path: .
          ### ##profile-name: myProfileName
          region: AWS_REGION
          repo: test8
          skip-when-tags-exist: false
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: test8_branch1
      - deploy-dev:
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: test8_branch1